name: flutter_auto_gui
description: A flutter plugin for desktop applications for controlling mouse and keyboard to automate interactions with other applications.
version: 0.0.1
homepage: https://flutter-auto-gui.chappie.dev/
repository: https://github.com/Chappie74/flutter_auto_gui/tree/main/flutter_auto_gui
environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    platforms:
      windows: 
        default_package: flutter_auto_gui_windows

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  flutter_auto_gui_windows: ^0.0.1
  flutter_auto_gui_platform_interface: ^0.0.2+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
