name: flutter_auto_gui
description: A new Flutter plugin project.
version: 0.0.1
environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    platforms:
      windows: 
        default_package: flutter_auto_gui_windows

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  flutter_auto_gui_windows: ^0.0.1
  flutter_auto_gui_platform_interface: ^0.0.2+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
