name: flutter_auto_gui_windows
description: Windows implementation of flutter_auto_gui plugin
version: 0.0.3
repository: https://github.com/Chappie74/flutter_auto_gui/tree/main/flutter_auto_gui_windows

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.0"

flutter:
  plugin:
    implements: flutter_auto_gui
    platforms:
      windows:
        pluginClass: FlutterAutoGuiWindows
        dartPluginClass: FlutterAutoGuiWindows

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  flutter_auto_gui_platform_interface: ^0.0.3
    


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  