name: flutter_auto_gui_platform_interface
description: Platform interface for flutter_auto_gui plugin
version: 0.0.2
homepage: https://github.com/Chappie74/flutter_auto_gui/tree/main/flutter_auto_gui


environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0